### ISSUE TITLE
Mobile Devices: System Requirements Not Met 

### ISSUE THREAD

**Issue by NoobFullStack** [DeBrabant45/Unity3d-City-Builder#1]
I was trying to use your City Builder application for mobile development, so i opened it up in Unity and simply converted all to mobile.. Off course, without success.. The error after build : System Requirements Not Met.. 

So i went the other way and copied the code and most scripts into a blanco Unity Mobile Project and almost at the end, i keep getting the following error and the screen just fades to black..  

```
NullReferenceException: Object reference not set to an instance of an object
GameManager.PrepareGameComponents () (at Assets/Scripts/GameManager.cs:75)
GameManager.Start () (at Assets/Scripts/GameManager.cs:68)
```

Snippets from the GameManager.cs : 

```
    // Start is called before the first frame update
    void Start()
    {
        //Any interface assignment needs to called before the buildingmanager is assigned or
        //you will get an object reference not set to an instance of an object
        _placementManager = placementManagerGameObject.GetComponent<IPlacementManager>();
        _resourceManager = resourceManagerGameObject.GetComponent<IResourceManager>();
        //
        worldManager.PrepareWorld(_cellSize, width, length);
        _placementManager.PreparePlacementManager(worldManager);
        _buildingManager = new BuildingManager(worldManager.Grid, _placementManager, structureRepository, _resourceManager);
        _resourceManager.PrepareResourceManager(_buildingManager);
        PrepareStates();
        PrepareGameComponents();    // line 68
        AssignInputListeners();
        AssignUIControllerListeners();
    }

    private void PrepareGameComponents()
    {
        inputManager.MouseInputMask = inputMask;    // line 75
        cameraMovement.SetCameraLimits(0, width, 0, length);
    }

```

I've checked and triple checked all visual variables, scripts and items in the Unity editor, though i'm not a coding here.. As your source code comments already mention, i need to **call the interface assignments before the buildingmanager**. But i cannot seems to perform this. What am i doing wrong? 

The code should work for mobile right?

**Comment by adebrabant** [comment]
Hello,

Based on the error your describing it's acting as if the public LayerMask inputMask has not been set in the Unity inspector, this game was made for desktop/web gl but I also don't see why it couldn't work on mobile. Please let me know if that field is populated.

![InputLayerMask](https://user-images.githubusercontent.com/22966649/105918927-c5394d00-6002-11eb-84a9-c27de1c3ac50.PNG)

**Comment by NoobFullStack** [comment]
Thank you very much for the quick response.  

I have included this Input Mask as Ground. All the fields that i can input in the Unity editor inspector are filled in exactly like you did in the example GameScene file. I haven't altered any code, as it was working perfectly in your GameScene example.. But i was suggested that the if statement might be stopping the inputManager assignement from getting executed, and therefor i get this error.. 
 

``` 
private void Awake() 
{
#if (UNITY_EDITOR && TEST || !(UNITY_IOS || UNITY_ANDROID) 
inputManager =  gameObject.AddComponent<InputManager>();
#endif
}
```

Have you been able to run it on Android?

**Comment by adebrabant** [comment]
That is entirely correct, within the awake I am setting the inputManager to the concrete implementation of the InputManager class. Looking further into this I would suggest creating a new class that inherits from the interface iInputManager and adding logic for mobile, since most of the logic in InputManager is specifically for mouse position. To answer the question on if I've ever ran this on Android, I have not. This was created as a webgl for my portfolio.  Below is an example of how you would want to set the inputManager field in awake to your newly created mobile input manager class.

```
#if (UNITY_IOS || UNITY_ANDROID) || !(UNITY_EDITOR && TEST)
inputManager =  gameObject.AddComponent<YourMobileInputManagerClassHere>();
#endif
```
